# This file now serves as a compatibility layer that redirects to storage.api
from zchat.storage.api import (
    init_app,
    create_initial_collections as create_indexes_to_meili,
    create_mindmaps_collection as create_mindmaps_index,
    add_mindmap as add_mindmap_to_meili,
    update_mindmap as update_mindmap_to_meili,
    get_mindmap as get_mindmap_from_meili,
    delete_mindmap as delete_mindmap_from_meili,
    create_user_mindmap_status_collection,
    add_user_mindmap_status as add_user_mindmap_status_to_meili,
    update_user_mindmap_status as update_user_mindmap_status_to_meili,
    upsert_user_mindmap_status as upsert_user_mindmap_status_to_meili,
    get_learning_status as get_learning_status_from_meili,
    get_learning_list as get_learning_list_from_meili,
    delete_collection as delete_index_from_meili,
    find_mindmaps_for_title as find_mindmaps_from_meili_for_title,
    find_user_mindmaps_created_by as find_user_mindmaps_from_meili_created_by,
    set_favorites as set_favorites_to_meili,
    get_favorites as get_favorites_from_meili,
    add_user_assessment_report as add_user_assessment_report_to_meili,
    get_user_assessment_report as get_user_assessment_report_from_meili,
    get_user_assessment_report_list as get_user_assessment_report_list_from_meili,
    add_feedback as add_feedback_to_meili,
    get_feedback as get_feedback_from_meili,
    update_feedback as update_feedback_to_meili,
    get_feedback_list as get_feedback_list_from_meili,
    add_file_records as add_file_records_to_meili,
    get_file_records as get_file_records_from_meili,
    update_file_records as update_file_records_to_meili,
)
