# This file now serves as a compatibility layer that redirects to storage.api
from zchat.storage.api import (
    init_app as init_storage_api,
    create_initial_collections as create_indexes_nosql,
    add_mindmap as add_mindmap_nosql,
    update_mindmap as update_mindmap_nosql,
    get_mindmap as get_mindmap_nosql,
    delete_mindmap as delete_mindmap_nosql,
    add_user_mindmap_status as add_user_mindmap_status_nosql,
    update_user_mindmap_status as update_user_mindmap_status_nosql,
    upsert_user_mindmap_status as upsert_user_mindmap_status_nosql,
    get_learning_status as get_learning_status_nosql,
    get_learning_list as get_learning_list_nosql,
    delete_collection as delete_index_nosql,
    set_favorites as set_favorites_nosql,
    get_favorites as get_favorites_nosql,
    add_user_assessment_report as add_user_assessment_report_nosql,
    get_user_assessment_report as get_user_assessment_report_nosql,
    get_user_assessment_report_list as get_user_assessment_report_list_nosql,
    add_feedback as add_feedback_nosql,
    get_feedback as get_feedback_nosql,
    update_feedback as update_feedback_nosql,
    get_feedback_list as get_feedback_list_nosql,
    add_file_records as add_file_records_nosql,
    get_file_records as get_file_records_nosql,
    update_file_records as update_file_records_nosql,
    add_resume_optimization_record as add_resume_optimization_record_nosql,
    get_resume_optimization_records as get_resume_optimization_records_nosql,
    add_jd_record as add_jd_record_nosql,
    get_jd_record as get_jd_record_nosql,
    get_jd_records as get_jd_records_nosql,
)
