"""add paddle price id for payment

Revision ID: 320e6d06f4de
Revises: b653ba7944da
Create Date: 2025-05-17 06:15:15.247756

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '320e6d06f4de'
down_revision = 'b653ba7944da'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('CHAT_MESSAGE', schema=None) as batch_op:
        batch_op.alter_column('timestamp',
               existing_type=mysql.DOUBLE(asdecimal=True),
               type_=sa.REAL(),
               existing_nullable=True)

    with op.batch_alter_table('CHAT_SESSION', schema=None) as batch_op:
        batch_op.alter_column('created_at',
               existing_type=mysql.DOUBLE(asdecimal=True),
               type_=sa.REAL(),
               existing_nullable=True)
        batch_op.alter_column('updated_at',
               existing_type=mysql.DOUBLE(asdecimal=True),
               type_=sa.REAL(),
               existing_nullable=True)

    with op.batch_alter_table('INVITATION', schema=None) as batch_op:
        batch_op.alter_column('created_at',
               existing_type=mysql.DOUBLE(asdecimal=True),
               type_=sa.REAL(),
               existing_nullable=False)

    with op.batch_alter_table('PAYMENT_ORDER', schema=None) as batch_op:
        batch_op.add_column(sa.Column('paddle_price_id', sa.String(length=64), nullable=True))
        batch_op.alter_column('amount',
               existing_type=mysql.DOUBLE(asdecimal=True),
               type_=sa.REAL(),
               existing_nullable=False)
        batch_op.alter_column('payment_time',
               existing_type=mysql.DOUBLE(asdecimal=True),
               type_=sa.REAL(),
               existing_nullable=True)
        batch_op.alter_column('created_at',
               existing_type=mysql.DOUBLE(asdecimal=True),
               type_=sa.REAL(),
               existing_nullable=False)
        batch_op.alter_column('updated_at',
               existing_type=mysql.DOUBLE(asdecimal=True),
               type_=sa.REAL(),
               existing_nullable=False)
        batch_op.create_index('index_PAYMENT_ORDER_order_type', ['order_type'], unique=False)
        batch_op.create_index('index_PAYMENT_ORDER_paddle_checkout_id', ['paddle_checkout_id'], unique=False)
        batch_op.create_index('index_PAYMENT_ORDER_paddle_payment_id', ['paddle_payment_id'], unique=False)
        batch_op.create_index('index_PAYMENT_ORDER_paddle_price_id', ['paddle_price_id'], unique=False)
        batch_op.create_index('index_PAYMENT_ORDER_paddle_subscription_id', ['paddle_subscription_id'], unique=False)
        batch_op.create_index('index_PAYMENT_ORDER_payment_method', ['payment_method'], unique=False)
        batch_op.create_index('index_PAYMENT_ORDER_transaction_id', ['transaction_id'], unique=False)

    with op.batch_alter_table('POINTS_BALANCE', schema=None) as batch_op:
        batch_op.alter_column('expires_at',
               existing_type=mysql.DOUBLE(asdecimal=True),
               type_=sa.REAL(),
               existing_nullable=True)
        batch_op.alter_column('created_at',
               existing_type=mysql.DOUBLE(asdecimal=True),
               type_=sa.REAL(),
               existing_nullable=False)

    with op.batch_alter_table('POINTS_TRANSACTION', schema=None) as batch_op:
        batch_op.alter_column('expires_at',
               existing_type=mysql.DOUBLE(asdecimal=True),
               type_=sa.REAL(),
               existing_nullable=True)
        batch_op.alter_column('created_at',
               existing_type=mysql.DOUBLE(asdecimal=True),
               type_=sa.REAL(),
               existing_nullable=False)

    with op.batch_alter_table('ROADMAP', schema=None) as batch_op:
        batch_op.alter_column('create_timestamp',
               existing_type=mysql.DOUBLE(asdecimal=True),
               type_=sa.REAL(),
               existing_nullable=True)
        batch_op.alter_column('update_timestamp',
               existing_type=mysql.DOUBLE(asdecimal=True),
               type_=sa.REAL(),
               existing_nullable=True)

    with op.batch_alter_table('SUBSCRIPTION', schema=None) as batch_op:
        batch_op.alter_column('start_time',
               existing_type=mysql.DOUBLE(asdecimal=True),
               type_=sa.REAL(),
               existing_nullable=False)
        batch_op.alter_column('end_time',
               existing_type=mysql.DOUBLE(asdecimal=True),
               type_=sa.REAL(),
               existing_nullable=False)
        batch_op.alter_column('payment_amount',
               existing_type=mysql.DOUBLE(asdecimal=True),
               type_=sa.REAL(),
               existing_nullable=False)
        batch_op.alter_column('created_at',
               existing_type=mysql.DOUBLE(asdecimal=True),
               type_=sa.REAL(),
               existing_nullable=False)

    with op.batch_alter_table('USER', schema=None) as batch_op:
        batch_op.alter_column('reset_token_expiry',
               existing_type=mysql.DOUBLE(asdecimal=True),
               type_=sa.REAL(),
               existing_nullable=True)
        batch_op.alter_column('points_reset_time',
               existing_type=mysql.DOUBLE(asdecimal=True),
               type_=sa.REAL(),
               existing_nullable=True)
        batch_op.alter_column('subscription_start_time',
               existing_type=mysql.DOUBLE(asdecimal=True),
               type_=sa.REAL(),
               existing_nullable=True)
        batch_op.alter_column('subscription_end_time',
               existing_type=mysql.DOUBLE(asdecimal=True),
               type_=sa.REAL(),
               existing_nullable=True)
        batch_op.alter_column('create_timestamp',
               existing_type=mysql.DOUBLE(asdecimal=True),
               type_=sa.REAL(),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('USER', schema=None) as batch_op:
        batch_op.alter_column('create_timestamp',
               existing_type=sa.REAL(),
               type_=mysql.DOUBLE(asdecimal=True),
               existing_nullable=True)
        batch_op.alter_column('subscription_end_time',
               existing_type=sa.REAL(),
               type_=mysql.DOUBLE(asdecimal=True),
               existing_nullable=True)
        batch_op.alter_column('subscription_start_time',
               existing_type=sa.REAL(),
               type_=mysql.DOUBLE(asdecimal=True),
               existing_nullable=True)
        batch_op.alter_column('points_reset_time',
               existing_type=sa.REAL(),
               type_=mysql.DOUBLE(asdecimal=True),
               existing_nullable=True)
        batch_op.alter_column('reset_token_expiry',
               existing_type=sa.REAL(),
               type_=mysql.DOUBLE(asdecimal=True),
               existing_nullable=True)

    with op.batch_alter_table('SUBSCRIPTION', schema=None) as batch_op:
        batch_op.alter_column('created_at',
               existing_type=sa.REAL(),
               type_=mysql.DOUBLE(asdecimal=True),
               existing_nullable=False)
        batch_op.alter_column('payment_amount',
               existing_type=sa.REAL(),
               type_=mysql.DOUBLE(asdecimal=True),
               existing_nullable=False)
        batch_op.alter_column('end_time',
               existing_type=sa.REAL(),
               type_=mysql.DOUBLE(asdecimal=True),
               existing_nullable=False)
        batch_op.alter_column('start_time',
               existing_type=sa.REAL(),
               type_=mysql.DOUBLE(asdecimal=True),
               existing_nullable=False)

    with op.batch_alter_table('ROADMAP', schema=None) as batch_op:
        batch_op.alter_column('update_timestamp',
               existing_type=sa.REAL(),
               type_=mysql.DOUBLE(asdecimal=True),
               existing_nullable=True)
        batch_op.alter_column('create_timestamp',
               existing_type=sa.REAL(),
               type_=mysql.DOUBLE(asdecimal=True),
               existing_nullable=True)

    with op.batch_alter_table('POINTS_TRANSACTION', schema=None) as batch_op:
        batch_op.alter_column('created_at',
               existing_type=sa.REAL(),
               type_=mysql.DOUBLE(asdecimal=True),
               existing_nullable=False)
        batch_op.alter_column('expires_at',
               existing_type=sa.REAL(),
               type_=mysql.DOUBLE(asdecimal=True),
               existing_nullable=True)

    with op.batch_alter_table('POINTS_BALANCE', schema=None) as batch_op:
        batch_op.alter_column('created_at',
               existing_type=sa.REAL(),
               type_=mysql.DOUBLE(asdecimal=True),
               existing_nullable=False)
        batch_op.alter_column('expires_at',
               existing_type=sa.REAL(),
               type_=mysql.DOUBLE(asdecimal=True),
               existing_nullable=True)

    with op.batch_alter_table('PAYMENT_ORDER', schema=None) as batch_op:
        batch_op.drop_index('index_PAYMENT_ORDER_transaction_id')
        batch_op.drop_index('index_PAYMENT_ORDER_payment_method')
        batch_op.drop_index('index_PAYMENT_ORDER_paddle_subscription_id')
        batch_op.drop_index('index_PAYMENT_ORDER_paddle_price_id')
        batch_op.drop_index('index_PAYMENT_ORDER_paddle_payment_id')
        batch_op.drop_index('index_PAYMENT_ORDER_paddle_checkout_id')
        batch_op.drop_index('index_PAYMENT_ORDER_order_type')
        batch_op.alter_column('updated_at',
               existing_type=sa.REAL(),
               type_=mysql.DOUBLE(asdecimal=True),
               existing_nullable=False)
        batch_op.alter_column('created_at',
               existing_type=sa.REAL(),
               type_=mysql.DOUBLE(asdecimal=True),
               existing_nullable=False)
        batch_op.alter_column('payment_time',
               existing_type=sa.REAL(),
               type_=mysql.DOUBLE(asdecimal=True),
               existing_nullable=True)
        batch_op.alter_column('amount',
               existing_type=sa.REAL(),
               type_=mysql.DOUBLE(asdecimal=True),
               existing_nullable=False)
        batch_op.drop_column('paddle_price_id')

    with op.batch_alter_table('INVITATION', schema=None) as batch_op:
        batch_op.alter_column('created_at',
               existing_type=sa.REAL(),
               type_=mysql.DOUBLE(asdecimal=True),
               existing_nullable=False)

    with op.batch_alter_table('CHAT_SESSION', schema=None) as batch_op:
        batch_op.alter_column('updated_at',
               existing_type=sa.REAL(),
               type_=mysql.DOUBLE(asdecimal=True),
               existing_nullable=True)
        batch_op.alter_column('created_at',
               existing_type=sa.REAL(),
               type_=mysql.DOUBLE(asdecimal=True),
               existing_nullable=True)

    with op.batch_alter_table('CHAT_MESSAGE', schema=None) as batch_op:
        batch_op.alter_column('timestamp',
               existing_type=sa.REAL(),
               type_=mysql.DOUBLE(asdecimal=True),
               existing_nullable=True)

    # ### end Alembic commands ###
