"""init

Revision ID: 35e1827d7a5b
Revises: 
Create Date: 2025-04-11 14:04:36.036886

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '35e1827d7a5b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ROADMAP',
    sa.Column('roadmap_id', sa.String(length=255), nullable=False),
    sa.Column('roadmap_icon', sa.String(length=255), nullable=False),
    sa.Column('roadmap_title', sa.String(length=255), nullable=False),
    sa.Column('roadmap_subtitle', sa.String(length=255), nullable=False),
    sa.Column('roadmap_type', sa.String(length=50), nullable=False),
    sa.Column('roadmap_kind', sa.String(length=50), nullable=False),
    sa.Column('roadmap_status', sa.Integer(), nullable=False),
    sa.Column('mindmap_id', sa.String(length=255), nullable=False),
    sa.Column('created_by', sa.String(length=255), nullable=True),
    sa.Column('industry_tag', sa.String(length=100), nullable=True),
    sa.Column('job_tag', sa.String(length=100), nullable=True),
    sa.Column('skill_tag', sa.String(length=100), nullable=True),
    sa.Column('create_timestamp', sa.REAL(), nullable=True),
    sa.Column('update_timestamp', sa.REAL(), nullable=True),
    sa.PrimaryKeyConstraint('roadmap_id')
    )
    with op.batch_alter_table('ROADMAP', schema=None) as batch_op:
        batch_op.create_index('index_ROADMAP_create_timestamp', ['create_timestamp'], unique=False)
        batch_op.create_index('index_ROADMAP_created_by', ['created_by'], unique=False)
        batch_op.create_index('index_ROADMAP_industry_tag', ['industry_tag'], unique=False)
        batch_op.create_index('index_ROADMAP_job_tag', ['job_tag'], unique=False)
        batch_op.create_index('index_ROADMAP_kind', ['roadmap_kind'], unique=False)
        batch_op.create_index('index_ROADMAP_mindmap_id', ['mindmap_id'], unique=False)
        batch_op.create_index('index_ROADMAP_skill_tag', ['skill_tag'], unique=False)
        batch_op.create_index('index_ROADMAP_status', ['roadmap_status'], unique=False)
        batch_op.create_index('index_ROADMAP_subtitle', ['roadmap_subtitle'], unique=False)
        batch_op.create_index('index_ROADMAP_title', ['roadmap_title'], unique=False)
        batch_op.create_index('index_ROADMAP_type', ['roadmap_type'], unique=False)
        batch_op.create_index('index_ROADMAP_update_timestamp', ['update_timestamp'], unique=False)

    op.create_table('ROADMAP_INTERACTION',
    sa.Column('roadmap_id', sa.String(length=255), nullable=False),
    sa.Column('user_id', sa.String(length=255), nullable=False),
    sa.Column('participanted', sa.Integer(), nullable=False),
    sa.Column('completed', sa.Integer(), nullable=False),
    sa.Column('favorited', sa.Integer(), nullable=False),
    sa.Column('shared', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('roadmap_id', 'user_id')
    )
    with op.batch_alter_table('ROADMAP_INTERACTION', schema=None) as batch_op:
        batch_op.create_index('index_ROADMAP_INTERACTION_completed', ['completed'], unique=False)
        batch_op.create_index('index_ROADMAP_INTERACTION_favorited', ['favorited'], unique=False)
        batch_op.create_index('index_ROADMAP_INTERACTION_participanted', ['participanted'], unique=False)
        batch_op.create_index('index_ROADMAP_INTERACTION_shared', ['shared'], unique=False)
        batch_op.create_index('index_ROADMAP_INTERACTION_user_id', ['user_id'], unique=False)

    op.create_table('USER',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('phone_number', sa.String(length=20), nullable=False),
    sa.Column('avatar_name', sa.String(length=255), nullable=False),
    sa.Column('nickname', sa.String(length=100), nullable=False),
    sa.Column('signature_text', sa.String(length=255), nullable=False),
    sa.Column('gender', sa.String(length=20), nullable=False),
    sa.Column('edubg', sa.String(length=50), nullable=False),
    sa.Column('yearofwork', sa.String(length=20), nullable=False),
    sa.Column('interested_industries', sa.String(length=500), nullable=True),
    sa.Column('interested_roles', sa.String(length=500), nullable=True),
    sa.Column('interested_skills', sa.String(length=500), nullable=True),
    sa.Column('account_type', sa.String(length=20), nullable=False),
    sa.Column('daily_points', sa.Integer(), nullable=False),
    sa.Column('points_reset_time', sa.REAL(), nullable=True),
    sa.Column('subscription_start_time', sa.REAL(), nullable=True),
    sa.Column('subscription_end_time', sa.REAL(), nullable=True),
    sa.Column('invite_code', sa.String(length=50), nullable=True),
    sa.Column('invited_by', sa.Integer(), nullable=True),
    sa.Column('create_timestamp', sa.REAL(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('USER', schema=None) as batch_op:
        batch_op.create_index('index_USER_account_type', ['account_type'], unique=False)
        batch_op.create_index('index_USER_create_timestamp', ['create_timestamp'], unique=False)
        batch_op.create_index('index_USER_edubg', ['edubg'], unique=False)
        batch_op.create_index('index_USER_gender', ['gender'], unique=False)
        batch_op.create_index('index_USER_invite_code', ['invite_code'], unique=True)
        batch_op.create_index('index_USER_invited_by', ['invited_by'], unique=False)
        batch_op.create_index('index_USER_name', ['nickname'], unique=False)
        batch_op.create_index('index_USER_phone_number', ['phone_number'], unique=True)
        batch_op.create_index('index_USER_signature_text', ['signature_text'], unique=False)
        batch_op.create_index('index_USER_yearofwork', ['yearofwork'], unique=False)

    op.create_table('ADMIN_USER',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['USER.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('CHAT_SESSION',
    sa.Column('id', sa.String(length=255), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('type', sa.String(length=50), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.REAL(), nullable=True),
    sa.Column('updated_at', sa.REAL(), nullable=True),
    sa.Column('is_archived', sa.Boolean(), nullable=True),
    sa.Column('session_metadata', sa.JSON(), nullable=True),
    sa.Column('roadmap_id', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['USER.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('CHAT_SESSION', schema=None) as batch_op:
        batch_op.create_index('index_CHAT_SESSION_created_at', ['created_at'], unique=False)
        batch_op.create_index('index_CHAT_SESSION_is_archived', ['is_archived'], unique=False)
        batch_op.create_index('index_CHAT_SESSION_roadmap_id', ['roadmap_id'], unique=False)
        batch_op.create_index('index_CHAT_SESSION_title', ['title'], unique=False)
        batch_op.create_index('index_CHAT_SESSION_type', ['type'], unique=False)
        batch_op.create_index('index_CHAT_SESSION_updated_at', ['updated_at'], unique=False)
        batch_op.create_index('index_CHAT_SESSION_user_id', ['user_id'], unique=False)

    op.create_table('INVITATION',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('inviter_id', sa.Integer(), nullable=False),
    sa.Column('invitee_id', sa.Integer(), nullable=False),
    sa.Column('points_rewarded', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.REAL(), nullable=False),
    sa.ForeignKeyConstraint(['invitee_id'], ['USER.id'], ),
    sa.ForeignKeyConstraint(['inviter_id'], ['USER.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('INVITATION', schema=None) as batch_op:
        batch_op.create_index('index_INVITATION_created_at', ['created_at'], unique=False)
        batch_op.create_index('index_INVITATION_invitee_id', ['invitee_id'], unique=False)
        batch_op.create_index('index_INVITATION_inviter_id', ['inviter_id'], unique=False)

    op.create_table('POINTS_BALANCE',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('points_amount', sa.Integer(), nullable=False),
    sa.Column('source_type', sa.String(length=50), nullable=False),
    sa.Column('expires_at', sa.REAL(), nullable=True),
    sa.Column('created_at', sa.REAL(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['USER.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('POINTS_BALANCE', schema=None) as batch_op:
        batch_op.create_index('index_POINTS_BALANCE_expires_at', ['expires_at'], unique=False)
        batch_op.create_index('index_POINTS_BALANCE_source_type', ['source_type'], unique=False)
        batch_op.create_index('index_POINTS_BALANCE_user_id', ['user_id'], unique=False)

    op.create_table('POINTS_TRANSACTION',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('transaction_type', sa.String(length=50), nullable=False),
    sa.Column('points_amount', sa.Integer(), nullable=False),
    sa.Column('service_type', sa.String(length=100), nullable=True),
    sa.Column('expires_at', sa.REAL(), nullable=True),
    sa.Column('created_at', sa.REAL(), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['USER.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('POINTS_TRANSACTION', schema=None) as batch_op:
        batch_op.create_index('index_POINTS_TRANSACTION_created_at', ['created_at'], unique=False)
        batch_op.create_index('index_POINTS_TRANSACTION_transaction_type', ['transaction_type'], unique=False)
        batch_op.create_index('index_POINTS_TRANSACTION_user_id', ['user_id'], unique=False)

    op.create_table('SUBSCRIPTION',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('subscription_type', sa.String(length=50), nullable=False),
    sa.Column('start_time', sa.REAL(), nullable=False),
    sa.Column('end_time', sa.REAL(), nullable=False),
    sa.Column('payment_amount', sa.REAL(), nullable=False),
    sa.Column('payment_method', sa.String(length=100), nullable=True),
    sa.Column('payment_order_id', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.REAL(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['USER.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('SUBSCRIPTION', schema=None) as batch_op:
        batch_op.create_index('index_SUBSCRIPTION_end_time', ['end_time'], unique=False)
        batch_op.create_index('index_SUBSCRIPTION_payment_order_id', ['payment_order_id'], unique=False)
        batch_op.create_index('index_SUBSCRIPTION_user_id', ['user_id'], unique=False)

    op.create_table('CHAT_MESSAGE',
    sa.Column('id', sa.String(length=255), nullable=False),
    sa.Column('session_id', sa.String(length=255), nullable=False),
    sa.Column('sender_type', sa.String(length=20), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('timestamp', sa.REAL(), nullable=True),
    sa.Column('message_metadata', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['session_id'], ['CHAT_SESSION.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('CHAT_MESSAGE', schema=None) as batch_op:
        batch_op.create_index('index_CHAT_MESSAGE_sender_type', ['sender_type'], unique=False)
        batch_op.create_index('index_CHAT_MESSAGE_session_id', ['session_id'], unique=False)
        batch_op.create_index('index_CHAT_MESSAGE_timestamp', ['timestamp'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('CHAT_MESSAGE', schema=None) as batch_op:
        batch_op.drop_index('index_CHAT_MESSAGE_timestamp')
        batch_op.drop_index('index_CHAT_MESSAGE_session_id')
        batch_op.drop_index('index_CHAT_MESSAGE_sender_type')

    op.drop_table('CHAT_MESSAGE')
    with op.batch_alter_table('SUBSCRIPTION', schema=None) as batch_op:
        batch_op.drop_index('index_SUBSCRIPTION_user_id')
        batch_op.drop_index('index_SUBSCRIPTION_payment_order_id')
        batch_op.drop_index('index_SUBSCRIPTION_end_time')

    op.drop_table('SUBSCRIPTION')
    with op.batch_alter_table('POINTS_TRANSACTION', schema=None) as batch_op:
        batch_op.drop_index('index_POINTS_TRANSACTION_user_id')
        batch_op.drop_index('index_POINTS_TRANSACTION_transaction_type')
        batch_op.drop_index('index_POINTS_TRANSACTION_created_at')

    op.drop_table('POINTS_TRANSACTION')
    with op.batch_alter_table('POINTS_BALANCE', schema=None) as batch_op:
        batch_op.drop_index('index_POINTS_BALANCE_user_id')
        batch_op.drop_index('index_POINTS_BALANCE_source_type')
        batch_op.drop_index('index_POINTS_BALANCE_expires_at')

    op.drop_table('POINTS_BALANCE')
    with op.batch_alter_table('INVITATION', schema=None) as batch_op:
        batch_op.drop_index('index_INVITATION_inviter_id')
        batch_op.drop_index('index_INVITATION_invitee_id')
        batch_op.drop_index('index_INVITATION_created_at')

    op.drop_table('INVITATION')
    with op.batch_alter_table('CHAT_SESSION', schema=None) as batch_op:
        batch_op.drop_index('index_CHAT_SESSION_user_id')
        batch_op.drop_index('index_CHAT_SESSION_updated_at')
        batch_op.drop_index('index_CHAT_SESSION_type')
        batch_op.drop_index('index_CHAT_SESSION_title')
        batch_op.drop_index('index_CHAT_SESSION_roadmap_id')
        batch_op.drop_index('index_CHAT_SESSION_is_archived')
        batch_op.drop_index('index_CHAT_SESSION_created_at')

    op.drop_table('CHAT_SESSION')
    op.drop_table('ADMIN_USER')
    with op.batch_alter_table('USER', schema=None) as batch_op:
        batch_op.drop_index('index_USER_yearofwork')
        batch_op.drop_index('index_USER_signature_text')
        batch_op.drop_index('index_USER_phone_number')
        batch_op.drop_index('index_USER_name')
        batch_op.drop_index('index_USER_invited_by')
        batch_op.drop_index('index_USER_invite_code')
        batch_op.drop_index('index_USER_gender')
        batch_op.drop_index('index_USER_edubg')
        batch_op.drop_index('index_USER_create_timestamp')
        batch_op.drop_index('index_USER_account_type')

    op.drop_table('USER')
    with op.batch_alter_table('ROADMAP_INTERACTION', schema=None) as batch_op:
        batch_op.drop_index('index_ROADMAP_INTERACTION_user_id')
        batch_op.drop_index('index_ROADMAP_INTERACTION_shared')
        batch_op.drop_index('index_ROADMAP_INTERACTION_participanted')
        batch_op.drop_index('index_ROADMAP_INTERACTION_favorited')
        batch_op.drop_index('index_ROADMAP_INTERACTION_completed')

    op.drop_table('ROADMAP_INTERACTION')
    with op.batch_alter_table('ROADMAP', schema=None) as batch_op:
        batch_op.drop_index('index_ROADMAP_update_timestamp')
        batch_op.drop_index('index_ROADMAP_type')
        batch_op.drop_index('index_ROADMAP_title')
        batch_op.drop_index('index_ROADMAP_subtitle')
        batch_op.drop_index('index_ROADMAP_status')
        batch_op.drop_index('index_ROADMAP_skill_tag')
        batch_op.drop_index('index_ROADMAP_mindmap_id')
        batch_op.drop_index('index_ROADMAP_kind')
        batch_op.drop_index('index_ROADMAP_job_tag')
        batch_op.drop_index('index_ROADMAP_industry_tag')
        batch_op.drop_index('index_ROADMAP_created_by')
        batch_op.drop_index('index_ROADMAP_create_timestamp')

    op.drop_table('ROADMAP')
    # ### end Alembic commands ###
