"""add skill tag length for roadmap

Revision ID: 369c76518d03
Revises: 678adebd6f6a
Create Date: 2025-05-27 09:11:46.017156

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '369c76518d03'
down_revision = '678adebd6f6a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('CHAT_MESSAGE', schema=None) as batch_op:
        batch_op.alter_column('timestamp',
               existing_type=mysql.DOUBLE(asdecimal=True),
               type_=sa.REAL(),
               existing_nullable=True)

    with op.batch_alter_table('CHAT_SESSION', schema=None) as batch_op:
        batch_op.alter_column('created_at',
               existing_type=mysql.DOUBLE(asdecimal=True),
               type_=sa.REAL(),
               existing_nullable=True)
        batch_op.alter_column('updated_at',
               existing_type=mysql.DOUBLE(asdecimal=True),
               type_=sa.REAL(),
               existing_nullable=True)

    with op.batch_alter_table('INVITATION', schema=None) as batch_op:
        batch_op.alter_column('created_at',
               existing_type=mysql.DOUBLE(asdecimal=True),
               type_=sa.REAL(),
               existing_nullable=False)

    with op.batch_alter_table('PAYMENT_ORDER', schema=None) as batch_op:
        batch_op.alter_column('amount',
               existing_type=mysql.DOUBLE(asdecimal=True),
               type_=sa.REAL(),
               existing_nullable=False)
        batch_op.alter_column('payment_time',
               existing_type=mysql.DOUBLE(asdecimal=True),
               type_=sa.REAL(),
               existing_nullable=True)
        batch_op.alter_column('created_at',
               existing_type=mysql.DOUBLE(asdecimal=True),
               type_=sa.REAL(),
               existing_nullable=False)
        batch_op.alter_column('updated_at',
               existing_type=mysql.DOUBLE(asdecimal=True),
               type_=sa.REAL(),
               existing_nullable=False)

    with op.batch_alter_table('POINTS_BALANCE', schema=None) as batch_op:
        batch_op.alter_column('expires_at',
               existing_type=mysql.DOUBLE(asdecimal=True),
               type_=sa.REAL(),
               existing_nullable=True)
        batch_op.alter_column('created_at',
               existing_type=mysql.DOUBLE(asdecimal=True),
               type_=sa.REAL(),
               existing_nullable=False)

    with op.batch_alter_table('POINTS_TRANSACTION', schema=None) as batch_op:
        batch_op.alter_column('expires_at',
               existing_type=mysql.DOUBLE(asdecimal=True),
               type_=sa.REAL(),
               existing_nullable=True)
        batch_op.alter_column('created_at',
               existing_type=mysql.DOUBLE(asdecimal=True),
               type_=sa.REAL(),
               existing_nullable=False)

    with op.batch_alter_table('ROADMAP', schema=None) as batch_op:
        batch_op.alter_column('industry_tag',
               existing_type=mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_unicode_ci', length=100),
               type_=sa.String(length=255),
               existing_nullable=True)
        batch_op.alter_column('job_tag',
               existing_type=mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_unicode_ci', length=100),
               type_=sa.String(length=255),
               existing_nullable=True)
        batch_op.alter_column('skill_tag',
               existing_type=mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_unicode_ci', length=100),
               type_=sa.String(length=255),
               existing_nullable=True)
        batch_op.alter_column('create_timestamp',
               existing_type=mysql.DOUBLE(asdecimal=True),
               type_=sa.REAL(),
               existing_nullable=True)
        batch_op.alter_column('update_timestamp',
               existing_type=mysql.DOUBLE(asdecimal=True),
               type_=sa.REAL(),
               existing_nullable=True)

    with op.batch_alter_table('SUBSCRIPTION', schema=None) as batch_op:
        batch_op.alter_column('start_time',
               existing_type=mysql.DOUBLE(asdecimal=True),
               type_=sa.REAL(),
               existing_nullable=False)
        batch_op.alter_column('end_time',
               existing_type=mysql.DOUBLE(asdecimal=True),
               type_=sa.REAL(),
               existing_nullable=False)
        batch_op.alter_column('payment_amount',
               existing_type=mysql.DOUBLE(asdecimal=True),
               type_=sa.REAL(),
               existing_nullable=False)
        batch_op.alter_column('created_at',
               existing_type=mysql.DOUBLE(asdecimal=True),
               type_=sa.REAL(),
               existing_nullable=False)

    with op.batch_alter_table('USER', schema=None) as batch_op:
        batch_op.alter_column('reset_token_expiry',
               existing_type=mysql.DOUBLE(asdecimal=True),
               type_=sa.REAL(),
               existing_nullable=True)
        batch_op.alter_column('points_reset_time',
               existing_type=mysql.DOUBLE(asdecimal=True),
               type_=sa.REAL(),
               existing_nullable=True)
        batch_op.alter_column('subscription_start_time',
               existing_type=mysql.DOUBLE(asdecimal=True),
               type_=sa.REAL(),
               existing_nullable=True)
        batch_op.alter_column('subscription_end_time',
               existing_type=mysql.DOUBLE(asdecimal=True),
               type_=sa.REAL(),
               existing_nullable=True)
        batch_op.alter_column('create_timestamp',
               existing_type=mysql.DOUBLE(asdecimal=True),
               type_=sa.REAL(),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('USER', schema=None) as batch_op:
        batch_op.alter_column('create_timestamp',
               existing_type=sa.REAL(),
               type_=mysql.DOUBLE(asdecimal=True),
               existing_nullable=True)
        batch_op.alter_column('subscription_end_time',
               existing_type=sa.REAL(),
               type_=mysql.DOUBLE(asdecimal=True),
               existing_nullable=True)
        batch_op.alter_column('subscription_start_time',
               existing_type=sa.REAL(),
               type_=mysql.DOUBLE(asdecimal=True),
               existing_nullable=True)
        batch_op.alter_column('points_reset_time',
               existing_type=sa.REAL(),
               type_=mysql.DOUBLE(asdecimal=True),
               existing_nullable=True)
        batch_op.alter_column('reset_token_expiry',
               existing_type=sa.REAL(),
               type_=mysql.DOUBLE(asdecimal=True),
               existing_nullable=True)

    with op.batch_alter_table('SUBSCRIPTION', schema=None) as batch_op:
        batch_op.alter_column('created_at',
               existing_type=sa.REAL(),
               type_=mysql.DOUBLE(asdecimal=True),
               existing_nullable=False)
        batch_op.alter_column('payment_amount',
               existing_type=sa.REAL(),
               type_=mysql.DOUBLE(asdecimal=True),
               existing_nullable=False)
        batch_op.alter_column('end_time',
               existing_type=sa.REAL(),
               type_=mysql.DOUBLE(asdecimal=True),
               existing_nullable=False)
        batch_op.alter_column('start_time',
               existing_type=sa.REAL(),
               type_=mysql.DOUBLE(asdecimal=True),
               existing_nullable=False)

    with op.batch_alter_table('ROADMAP', schema=None) as batch_op:
        batch_op.alter_column('update_timestamp',
               existing_type=sa.REAL(),
               type_=mysql.DOUBLE(asdecimal=True),
               existing_nullable=True)
        batch_op.alter_column('create_timestamp',
               existing_type=sa.REAL(),
               type_=mysql.DOUBLE(asdecimal=True),
               existing_nullable=True)
        batch_op.alter_column('skill_tag',
               existing_type=sa.String(length=255),
               type_=mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_unicode_ci', length=100),
               existing_nullable=True)
        batch_op.alter_column('job_tag',
               existing_type=sa.String(length=255),
               type_=mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_unicode_ci', length=100),
               existing_nullable=True)
        batch_op.alter_column('industry_tag',
               existing_type=sa.String(length=255),
               type_=mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_unicode_ci', length=100),
               existing_nullable=True)

    with op.batch_alter_table('POINTS_TRANSACTION', schema=None) as batch_op:
        batch_op.alter_column('created_at',
               existing_type=sa.REAL(),
               type_=mysql.DOUBLE(asdecimal=True),
               existing_nullable=False)
        batch_op.alter_column('expires_at',
               existing_type=sa.REAL(),
               type_=mysql.DOUBLE(asdecimal=True),
               existing_nullable=True)

    with op.batch_alter_table('POINTS_BALANCE', schema=None) as batch_op:
        batch_op.alter_column('created_at',
               existing_type=sa.REAL(),
               type_=mysql.DOUBLE(asdecimal=True),
               existing_nullable=False)
        batch_op.alter_column('expires_at',
               existing_type=sa.REAL(),
               type_=mysql.DOUBLE(asdecimal=True),
               existing_nullable=True)

    with op.batch_alter_table('PAYMENT_ORDER', schema=None) as batch_op:
        batch_op.alter_column('updated_at',
               existing_type=sa.REAL(),
               type_=mysql.DOUBLE(asdecimal=True),
               existing_nullable=False)
        batch_op.alter_column('created_at',
               existing_type=sa.REAL(),
               type_=mysql.DOUBLE(asdecimal=True),
               existing_nullable=False)
        batch_op.alter_column('payment_time',
               existing_type=sa.REAL(),
               type_=mysql.DOUBLE(asdecimal=True),
               existing_nullable=True)
        batch_op.alter_column('amount',
               existing_type=sa.REAL(),
               type_=mysql.DOUBLE(asdecimal=True),
               existing_nullable=False)

    with op.batch_alter_table('INVITATION', schema=None) as batch_op:
        batch_op.alter_column('created_at',
               existing_type=sa.REAL(),
               type_=mysql.DOUBLE(asdecimal=True),
               existing_nullable=False)

    with op.batch_alter_table('CHAT_SESSION', schema=None) as batch_op:
        batch_op.alter_column('updated_at',
               existing_type=sa.REAL(),
               type_=mysql.DOUBLE(asdecimal=True),
               existing_nullable=True)
        batch_op.alter_column('created_at',
               existing_type=sa.REAL(),
               type_=mysql.DOUBLE(asdecimal=True),
               existing_nullable=True)

    with op.batch_alter_table('CHAT_MESSAGE', schema=None) as batch_op:
        batch_op.alter_column('timestamp',
               existing_type=sa.REAL(),
               type_=mysql.DOUBLE(asdecimal=True),
               existing_nullable=True)

    # ### end Alembic commands ###
