"""update, add payment

Revision ID: 504bb10c81e6
Revises: 5810f9a37ea9
Create Date: 2025-04-17 16:50:33.816692

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '504bb10c81e6'
down_revision = '5810f9a37ea9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('CHAT_MESSAGE', schema=None) as batch_op:
        batch_op.alter_column('timestamp',
               existing_type=mysql.DOUBLE(asdecimal=True),
               type_=sa.REAL(),
               existing_nullable=True)

    with op.batch_alter_table('CHAT_SESSION', schema=None) as batch_op:
        batch_op.alter_column('created_at',
               existing_type=mysql.DOUBLE(asdecimal=True),
               type_=sa.REAL(),
               existing_nullable=True)
        batch_op.alter_column('updated_at',
               existing_type=mysql.DOUBLE(asdecimal=True),
               type_=sa.REAL(),
               existing_nullable=True)

    with op.batch_alter_table('INVITATION', schema=None) as batch_op:
        batch_op.alter_column('created_at',
               existing_type=mysql.DOUBLE(asdecimal=True),
               type_=sa.REAL(),
               existing_nullable=False)

    with op.batch_alter_table('PAYMENT_ORDER', schema=None) as batch_op:
        batch_op.alter_column('amount',
               existing_type=mysql.DOUBLE(asdecimal=True),
               type_=sa.REAL(),
               existing_nullable=False)
        batch_op.alter_column('payment_time',
               existing_type=mysql.DOUBLE(asdecimal=True),
               type_=sa.REAL(),
               existing_nullable=True)
        batch_op.alter_column('created_at',
               existing_type=mysql.DOUBLE(asdecimal=True),
               type_=sa.REAL(),
               existing_nullable=False)
        batch_op.alter_column('updated_at',
               existing_type=mysql.DOUBLE(asdecimal=True),
               type_=sa.REAL(),
               existing_nullable=False)

    with op.batch_alter_table('POINTS_BALANCE', schema=None) as batch_op:
        batch_op.alter_column('expires_at',
               existing_type=mysql.DOUBLE(asdecimal=True),
               type_=sa.REAL(),
               existing_nullable=True)
        batch_op.alter_column('created_at',
               existing_type=mysql.DOUBLE(asdecimal=True),
               type_=sa.REAL(),
               existing_nullable=False)

    with op.batch_alter_table('POINTS_TRANSACTION', schema=None) as batch_op:
        batch_op.alter_column('expires_at',
               existing_type=mysql.DOUBLE(asdecimal=True),
               type_=sa.REAL(),
               existing_nullable=True)
        batch_op.alter_column('created_at',
               existing_type=mysql.DOUBLE(asdecimal=True),
               type_=sa.REAL(),
               existing_nullable=False)

    with op.batch_alter_table('ROADMAP', schema=None) as batch_op:
        batch_op.alter_column('create_timestamp',
               existing_type=mysql.DOUBLE(asdecimal=True),
               type_=sa.REAL(),
               existing_nullable=True)
        batch_op.alter_column('update_timestamp',
               existing_type=mysql.DOUBLE(asdecimal=True),
               type_=sa.REAL(),
               existing_nullable=True)

    with op.batch_alter_table('SUBSCRIPTION', schema=None) as batch_op:
        batch_op.alter_column('start_time',
               existing_type=mysql.DOUBLE(asdecimal=True),
               type_=sa.REAL(),
               existing_nullable=False)
        batch_op.alter_column('end_time',
               existing_type=mysql.DOUBLE(asdecimal=True),
               type_=sa.REAL(),
               existing_nullable=False)
        batch_op.alter_column('payment_amount',
               existing_type=mysql.DOUBLE(asdecimal=True),
               type_=sa.REAL(),
               existing_nullable=False)
        batch_op.alter_column('created_at',
               existing_type=mysql.DOUBLE(asdecimal=True),
               type_=sa.REAL(),
               existing_nullable=False)

    with op.batch_alter_table('USER', schema=None) as batch_op:
        batch_op.alter_column('points_reset_time',
               existing_type=mysql.DOUBLE(asdecimal=True),
               type_=sa.REAL(),
               existing_nullable=True)
        batch_op.alter_column('subscription_start_time',
               existing_type=mysql.DOUBLE(asdecimal=True),
               type_=sa.REAL(),
               existing_nullable=True)
        batch_op.alter_column('subscription_end_time',
               existing_type=mysql.DOUBLE(asdecimal=True),
               type_=sa.REAL(),
               existing_nullable=True)
        batch_op.alter_column('create_timestamp',
               existing_type=mysql.DOUBLE(asdecimal=True),
               type_=sa.REAL(),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('USER', schema=None) as batch_op:
        batch_op.alter_column('create_timestamp',
               existing_type=sa.REAL(),
               type_=mysql.DOUBLE(asdecimal=True),
               existing_nullable=True)
        batch_op.alter_column('subscription_end_time',
               existing_type=sa.REAL(),
               type_=mysql.DOUBLE(asdecimal=True),
               existing_nullable=True)
        batch_op.alter_column('subscription_start_time',
               existing_type=sa.REAL(),
               type_=mysql.DOUBLE(asdecimal=True),
               existing_nullable=True)
        batch_op.alter_column('points_reset_time',
               existing_type=sa.REAL(),
               type_=mysql.DOUBLE(asdecimal=True),
               existing_nullable=True)

    with op.batch_alter_table('SUBSCRIPTION', schema=None) as batch_op:
        batch_op.alter_column('created_at',
               existing_type=sa.REAL(),
               type_=mysql.DOUBLE(asdecimal=True),
               existing_nullable=False)
        batch_op.alter_column('payment_amount',
               existing_type=sa.REAL(),
               type_=mysql.DOUBLE(asdecimal=True),
               existing_nullable=False)
        batch_op.alter_column('end_time',
               existing_type=sa.REAL(),
               type_=mysql.DOUBLE(asdecimal=True),
               existing_nullable=False)
        batch_op.alter_column('start_time',
               existing_type=sa.REAL(),
               type_=mysql.DOUBLE(asdecimal=True),
               existing_nullable=False)

    with op.batch_alter_table('ROADMAP', schema=None) as batch_op:
        batch_op.alter_column('update_timestamp',
               existing_type=sa.REAL(),
               type_=mysql.DOUBLE(asdecimal=True),
               existing_nullable=True)
        batch_op.alter_column('create_timestamp',
               existing_type=sa.REAL(),
               type_=mysql.DOUBLE(asdecimal=True),
               existing_nullable=True)

    with op.batch_alter_table('POINTS_TRANSACTION', schema=None) as batch_op:
        batch_op.alter_column('created_at',
               existing_type=sa.REAL(),
               type_=mysql.DOUBLE(asdecimal=True),
               existing_nullable=False)
        batch_op.alter_column('expires_at',
               existing_type=sa.REAL(),
               type_=mysql.DOUBLE(asdecimal=True),
               existing_nullable=True)

    with op.batch_alter_table('POINTS_BALANCE', schema=None) as batch_op:
        batch_op.alter_column('created_at',
               existing_type=sa.REAL(),
               type_=mysql.DOUBLE(asdecimal=True),
               existing_nullable=False)
        batch_op.alter_column('expires_at',
               existing_type=sa.REAL(),
               type_=mysql.DOUBLE(asdecimal=True),
               existing_nullable=True)

    with op.batch_alter_table('PAYMENT_ORDER', schema=None) as batch_op:
        batch_op.alter_column('updated_at',
               existing_type=sa.REAL(),
               type_=mysql.DOUBLE(asdecimal=True),
               existing_nullable=False)
        batch_op.alter_column('created_at',
               existing_type=sa.REAL(),
               type_=mysql.DOUBLE(asdecimal=True),
               existing_nullable=False)
        batch_op.alter_column('payment_time',
               existing_type=sa.REAL(),
               type_=mysql.DOUBLE(asdecimal=True),
               existing_nullable=True)
        batch_op.alter_column('amount',
               existing_type=sa.REAL(),
               type_=mysql.DOUBLE(asdecimal=True),
               existing_nullable=False)

    with op.batch_alter_table('INVITATION', schema=None) as batch_op:
        batch_op.alter_column('created_at',
               existing_type=sa.REAL(),
               type_=mysql.DOUBLE(asdecimal=True),
               existing_nullable=False)

    with op.batch_alter_table('CHAT_SESSION', schema=None) as batch_op:
        batch_op.alter_column('updated_at',
               existing_type=sa.REAL(),
               type_=mysql.DOUBLE(asdecimal=True),
               existing_nullable=True)
        batch_op.alter_column('created_at',
               existing_type=sa.REAL(),
               type_=mysql.DOUBLE(asdecimal=True),
               existing_nullable=True)

    with op.batch_alter_table('CHAT_MESSAGE', schema=None) as batch_op:
        batch_op.alter_column('timestamp',
               existing_type=sa.REAL(),
               type_=mysql.DOUBLE(asdecimal=True),
               existing_nullable=True)

    # ### end Alembic commands ###
