"""add alipay payment

Revision ID: 8bf1699b67d7
Revises: 35e1827d7a5b
Create Date: 2025-04-15 10:11:34.224361

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '8bf1699b67d7'
down_revision = '35e1827d7a5b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('PAYMENT_ORDER',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('order_id', sa.String(length=64), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('order_type', sa.String(length=50), nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=True),
    sa.Column('amount', sa.REAL(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('payment_method', sa.String(length=50), nullable=False),
    sa.Column('transaction_id', sa.String(length=64), nullable=True),
    sa.Column('payment_time', sa.REAL(), nullable=True),
    sa.Column('extra_data', sa.Text(), nullable=True),
    sa.Column('created_at', sa.REAL(), nullable=False),
    sa.Column('updated_at', sa.REAL(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['USER.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('order_id')
    )
    with op.batch_alter_table('PAYMENT_ORDER', schema=None) as batch_op:
        batch_op.create_index('index_PAYMENT_ORDER_created_at', ['created_at'], unique=False)
        batch_op.create_index('index_PAYMENT_ORDER_order_id', ['order_id'], unique=False)
        batch_op.create_index('index_PAYMENT_ORDER_status', ['status'], unique=False)
        batch_op.create_index('index_PAYMENT_ORDER_user_id', ['user_id'], unique=False)

    op.drop_table('indexed_fields')
    with op.batch_alter_table('documents', schema=None) as batch_op:
        batch_op.drop_index('idx_documents_updated')

    op.drop_table('documents')
    op.drop_table('collections')
    with op.batch_alter_table('field_values', schema=None) as batch_op:
        batch_op.drop_index('idx_field_values_lookup')
        batch_op.drop_index('idx_field_values_value', mysql_length={'field_value': 50})
        batch_op.drop_index('unique_field_value', mysql_length={'field_value': 50})

    op.drop_table('field_values')
    with op.batch_alter_table('CHAT_MESSAGE', schema=None) as batch_op:
        batch_op.alter_column('timestamp',
               existing_type=mysql.DOUBLE(asdecimal=True),
               type_=sa.REAL(),
               existing_nullable=True)

    with op.batch_alter_table('CHAT_SESSION', schema=None) as batch_op:
        batch_op.alter_column('created_at',
               existing_type=mysql.DOUBLE(asdecimal=True),
               type_=sa.REAL(),
               existing_nullable=True)
        batch_op.alter_column('updated_at',
               existing_type=mysql.DOUBLE(asdecimal=True),
               type_=sa.REAL(),
               existing_nullable=True)

    with op.batch_alter_table('INVITATION', schema=None) as batch_op:
        batch_op.alter_column('created_at',
               existing_type=mysql.DOUBLE(asdecimal=True),
               type_=sa.REAL(),
               existing_nullable=False)

    with op.batch_alter_table('POINTS_BALANCE', schema=None) as batch_op:
        batch_op.alter_column('expires_at',
               existing_type=mysql.DOUBLE(asdecimal=True),
               type_=sa.REAL(),
               existing_nullable=True)
        batch_op.alter_column('created_at',
               existing_type=mysql.DOUBLE(asdecimal=True),
               type_=sa.REAL(),
               existing_nullable=False)

    with op.batch_alter_table('POINTS_TRANSACTION', schema=None) as batch_op:
        batch_op.alter_column('expires_at',
               existing_type=mysql.DOUBLE(asdecimal=True),
               type_=sa.REAL(),
               existing_nullable=True)
        batch_op.alter_column('created_at',
               existing_type=mysql.DOUBLE(asdecimal=True),
               type_=sa.REAL(),
               existing_nullable=False)

    with op.batch_alter_table('ROADMAP', schema=None) as batch_op:
        batch_op.alter_column('create_timestamp',
               existing_type=mysql.DOUBLE(asdecimal=True),
               type_=sa.REAL(),
               existing_nullable=True)
        batch_op.alter_column('update_timestamp',
               existing_type=mysql.DOUBLE(asdecimal=True),
               type_=sa.REAL(),
               existing_nullable=True)

    with op.batch_alter_table('SUBSCRIPTION', schema=None) as batch_op:
        batch_op.alter_column('start_time',
               existing_type=mysql.DOUBLE(asdecimal=True),
               type_=sa.REAL(),
               existing_nullable=False)
        batch_op.alter_column('end_time',
               existing_type=mysql.DOUBLE(asdecimal=True),
               type_=sa.REAL(),
               existing_nullable=False)
        batch_op.alter_column('payment_amount',
               existing_type=mysql.DOUBLE(asdecimal=True),
               type_=sa.REAL(),
               existing_nullable=False)
        batch_op.alter_column('created_at',
               existing_type=mysql.DOUBLE(asdecimal=True),
               type_=sa.REAL(),
               existing_nullable=False)

    with op.batch_alter_table('USER', schema=None) as batch_op:
        batch_op.alter_column('points_reset_time',
               existing_type=mysql.DOUBLE(asdecimal=True),
               type_=sa.REAL(),
               existing_nullable=True)
        batch_op.alter_column('subscription_start_time',
               existing_type=mysql.DOUBLE(asdecimal=True),
               type_=sa.REAL(),
               existing_nullable=True)
        batch_op.alter_column('subscription_end_time',
               existing_type=mysql.DOUBLE(asdecimal=True),
               type_=sa.REAL(),
               existing_nullable=True)
        batch_op.alter_column('create_timestamp',
               existing_type=mysql.DOUBLE(asdecimal=True),
               type_=sa.REAL(),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('USER', schema=None) as batch_op:
        batch_op.alter_column('create_timestamp',
               existing_type=sa.REAL(),
               type_=mysql.DOUBLE(asdecimal=True),
               existing_nullable=True)
        batch_op.alter_column('subscription_end_time',
               existing_type=sa.REAL(),
               type_=mysql.DOUBLE(asdecimal=True),
               existing_nullable=True)
        batch_op.alter_column('subscription_start_time',
               existing_type=sa.REAL(),
               type_=mysql.DOUBLE(asdecimal=True),
               existing_nullable=True)
        batch_op.alter_column('points_reset_time',
               existing_type=sa.REAL(),
               type_=mysql.DOUBLE(asdecimal=True),
               existing_nullable=True)

    with op.batch_alter_table('SUBSCRIPTION', schema=None) as batch_op:
        batch_op.alter_column('created_at',
               existing_type=sa.REAL(),
               type_=mysql.DOUBLE(asdecimal=True),
               existing_nullable=False)
        batch_op.alter_column('payment_amount',
               existing_type=sa.REAL(),
               type_=mysql.DOUBLE(asdecimal=True),
               existing_nullable=False)
        batch_op.alter_column('end_time',
               existing_type=sa.REAL(),
               type_=mysql.DOUBLE(asdecimal=True),
               existing_nullable=False)
        batch_op.alter_column('start_time',
               existing_type=sa.REAL(),
               type_=mysql.DOUBLE(asdecimal=True),
               existing_nullable=False)

    with op.batch_alter_table('ROADMAP', schema=None) as batch_op:
        batch_op.alter_column('update_timestamp',
               existing_type=sa.REAL(),
               type_=mysql.DOUBLE(asdecimal=True),
               existing_nullable=True)
        batch_op.alter_column('create_timestamp',
               existing_type=sa.REAL(),
               type_=mysql.DOUBLE(asdecimal=True),
               existing_nullable=True)

    with op.batch_alter_table('POINTS_TRANSACTION', schema=None) as batch_op:
        batch_op.alter_column('created_at',
               existing_type=sa.REAL(),
               type_=mysql.DOUBLE(asdecimal=True),
               existing_nullable=False)
        batch_op.alter_column('expires_at',
               existing_type=sa.REAL(),
               type_=mysql.DOUBLE(asdecimal=True),
               existing_nullable=True)

    with op.batch_alter_table('POINTS_BALANCE', schema=None) as batch_op:
        batch_op.alter_column('created_at',
               existing_type=sa.REAL(),
               type_=mysql.DOUBLE(asdecimal=True),
               existing_nullable=False)
        batch_op.alter_column('expires_at',
               existing_type=sa.REAL(),
               type_=mysql.DOUBLE(asdecimal=True),
               existing_nullable=True)

    with op.batch_alter_table('INVITATION', schema=None) as batch_op:
        batch_op.alter_column('created_at',
               existing_type=sa.REAL(),
               type_=mysql.DOUBLE(asdecimal=True),
               existing_nullable=False)

    with op.batch_alter_table('CHAT_SESSION', schema=None) as batch_op:
        batch_op.alter_column('updated_at',
               existing_type=sa.REAL(),
               type_=mysql.DOUBLE(asdecimal=True),
               existing_nullable=True)
        batch_op.alter_column('created_at',
               existing_type=sa.REAL(),
               type_=mysql.DOUBLE(asdecimal=True),
               existing_nullable=True)

    with op.batch_alter_table('CHAT_MESSAGE', schema=None) as batch_op:
        batch_op.alter_column('timestamp',
               existing_type=sa.REAL(),
               type_=mysql.DOUBLE(asdecimal=True),
               existing_nullable=True)

    op.create_table('field_values',
    sa.Column('id', mysql.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('collection_name', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=100), nullable=False),
    sa.Column('field_name', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=100), nullable=False),
    sa.Column('field_value', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=100), nullable=False),
    sa.Column('doc_id', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=100), nullable=False),
    sa.ForeignKeyConstraint(['collection_name', 'doc_id'], ['documents.collection_name', 'documents.doc_id'], name='fk_field_doc', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['collection_name', 'field_name'], ['indexed_fields.collection_name', 'indexed_fields.field_name'], name='fk_field_idx', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_unicode_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('field_values', schema=None) as batch_op:
        batch_op.create_index('unique_field_value', ['collection_name', 'field_name', 'field_value', 'doc_id'], unique=True, mysql_length={'field_value': 50})
        batch_op.create_index('idx_field_values_value', ['field_value'], unique=False, mysql_length={'field_value': 50})
        batch_op.create_index('idx_field_values_lookup', ['collection_name', 'field_name', 'doc_id'], unique=False)

    op.create_table('collections',
    sa.Column('name', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=100), nullable=False),
    sa.Column('primary_key', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=100), nullable=False),
    sa.Column('created_at', mysql.DOUBLE(asdecimal=True), nullable=False),
    sa.Column('options', mysql.TEXT(collation='utf8mb4_unicode_ci'), nullable=True),
    sa.PrimaryKeyConstraint('name'),
    mysql_collate='utf8mb4_unicode_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('documents',
    sa.Column('collection_name', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=100), nullable=False),
    sa.Column('doc_id', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=100), nullable=False),
    sa.Column('content', mysql.LONGTEXT(collation='utf8mb4_unicode_ci'), nullable=False),
    sa.Column('created_at', mysql.DOUBLE(asdecimal=True), nullable=False),
    sa.Column('updated_at', mysql.DOUBLE(asdecimal=True), nullable=False),
    sa.ForeignKeyConstraint(['collection_name'], ['collections.name'], name='fk_coll_name', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('collection_name', 'doc_id'),
    mysql_collate='utf8mb4_unicode_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('documents', schema=None) as batch_op:
        batch_op.create_index('idx_documents_updated', ['updated_at'], unique=False)

    op.create_table('indexed_fields',
    sa.Column('collection_name', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=100), nullable=False),
    sa.Column('field_name', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=100), nullable=False),
    sa.ForeignKeyConstraint(['collection_name'], ['collections.name'], name='fk_idx_coll_name', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('collection_name', 'field_name'),
    mysql_collate='utf8mb4_unicode_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('PAYMENT_ORDER', schema=None) as batch_op:
        batch_op.drop_index('index_PAYMENT_ORDER_user_id')
        batch_op.drop_index('index_PAYMENT_ORDER_status')
        batch_op.drop_index('index_PAYMENT_ORDER_order_id')
        batch_op.drop_index('index_PAYMENT_ORDER_created_at')

    op.drop_table('PAYMENT_ORDER')
    # ### end Alembic commands ###
