"""upgrade auth

Revision ID: f95f05996d43
Revises: ade7084b77ba
Create Date: 2025-05-02 13:46:50.176511

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'f95f05996d43'
down_revision = 'ade7084b77ba'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('CHAT_MESSAGE', schema=None) as batch_op:
        batch_op.alter_column('timestamp',
               existing_type=mysql.DOUBLE(asdecimal=True),
               type_=sa.REAL(),
               existing_nullable=True)

    with op.batch_alter_table('CHAT_SESSION', schema=None) as batch_op:
        batch_op.alter_column('created_at',
               existing_type=mysql.DOUBLE(asdecimal=True),
               type_=sa.REAL(),
               existing_nullable=True)
        batch_op.alter_column('updated_at',
               existing_type=mysql.DOUBLE(asdecimal=True),
               type_=sa.REAL(),
               existing_nullable=True)

    with op.batch_alter_table('INVITATION', schema=None) as batch_op:
        batch_op.alter_column('created_at',
               existing_type=mysql.DOUBLE(asdecimal=True),
               type_=sa.REAL(),
               existing_nullable=False)

    with op.batch_alter_table('PAYMENT_ORDER', schema=None) as batch_op:
        batch_op.alter_column('amount',
               existing_type=mysql.DOUBLE(asdecimal=True),
               type_=sa.REAL(),
               existing_nullable=False)
        batch_op.alter_column('payment_time',
               existing_type=mysql.DOUBLE(asdecimal=True),
               type_=sa.REAL(),
               existing_nullable=True)
        batch_op.alter_column('created_at',
               existing_type=mysql.DOUBLE(asdecimal=True),
               type_=sa.REAL(),
               existing_nullable=False)
        batch_op.alter_column('updated_at',
               existing_type=mysql.DOUBLE(asdecimal=True),
               type_=sa.REAL(),
               existing_nullable=False)

    with op.batch_alter_table('POINTS_BALANCE', schema=None) as batch_op:
        batch_op.alter_column('expires_at',
               existing_type=mysql.DOUBLE(asdecimal=True),
               type_=sa.REAL(),
               existing_nullable=True)
        batch_op.alter_column('created_at',
               existing_type=mysql.DOUBLE(asdecimal=True),
               type_=sa.REAL(),
               existing_nullable=False)

    with op.batch_alter_table('POINTS_TRANSACTION', schema=None) as batch_op:
        batch_op.alter_column('expires_at',
               existing_type=mysql.DOUBLE(asdecimal=True),
               type_=sa.REAL(),
               existing_nullable=True)
        batch_op.alter_column('created_at',
               existing_type=mysql.DOUBLE(asdecimal=True),
               type_=sa.REAL(),
               existing_nullable=False)

    with op.batch_alter_table('ROADMAP', schema=None) as batch_op:
        batch_op.alter_column('create_timestamp',
               existing_type=mysql.DOUBLE(asdecimal=True),
               type_=sa.REAL(),
               existing_nullable=True)
        batch_op.alter_column('update_timestamp',
               existing_type=mysql.DOUBLE(asdecimal=True),
               type_=sa.REAL(),
               existing_nullable=True)

    with op.batch_alter_table('SUBSCRIPTION', schema=None) as batch_op:
        batch_op.alter_column('start_time',
               existing_type=mysql.DOUBLE(asdecimal=True),
               type_=sa.REAL(),
               existing_nullable=False)
        batch_op.alter_column('end_time',
               existing_type=mysql.DOUBLE(asdecimal=True),
               type_=sa.REAL(),
               existing_nullable=False)
        batch_op.alter_column('payment_amount',
               existing_type=mysql.DOUBLE(asdecimal=True),
               type_=sa.REAL(),
               existing_nullable=False)
        batch_op.alter_column('created_at',
               existing_type=mysql.DOUBLE(asdecimal=True),
               type_=sa.REAL(),
               existing_nullable=False)

    with op.batch_alter_table('USER', schema=None) as batch_op:
        batch_op.add_column(sa.Column('email', sa.String(length=120), nullable=True))
        batch_op.add_column(sa.Column('email_verified', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('password_hash', sa.String(length=256), nullable=True))
        batch_op.add_column(sa.Column('reset_token', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('reset_token_expiry', sa.REAL(), nullable=True))
        batch_op.add_column(sa.Column('oauth_provider', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('oauth_id', sa.String(length=100), nullable=True))
        batch_op.alter_column('phone_number',
               existing_type=mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_unicode_ci', length=20),
               nullable=True)
        batch_op.alter_column('points_reset_time',
               existing_type=mysql.DOUBLE(asdecimal=True),
               type_=sa.REAL(),
               existing_nullable=True)
        batch_op.alter_column('subscription_start_time',
               existing_type=mysql.DOUBLE(asdecimal=True),
               type_=sa.REAL(),
               existing_nullable=True)
        batch_op.alter_column('subscription_end_time',
               existing_type=mysql.DOUBLE(asdecimal=True),
               type_=sa.REAL(),
               existing_nullable=True)
        batch_op.alter_column('create_timestamp',
               existing_type=mysql.DOUBLE(asdecimal=True),
               type_=sa.REAL(),
               existing_nullable=True)
        batch_op.create_index('index_USER_email', ['email'], unique=True)
        batch_op.create_index('index_USER_oauth_provider_id', ['oauth_provider', 'oauth_id'], unique=True)
        batch_op.create_unique_constraint(None, ['email'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('USER', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_index('index_USER_oauth_provider_id')
        batch_op.drop_index('index_USER_email')
        batch_op.alter_column('create_timestamp',
               existing_type=sa.REAL(),
               type_=mysql.DOUBLE(asdecimal=True),
               existing_nullable=True)
        batch_op.alter_column('subscription_end_time',
               existing_type=sa.REAL(),
               type_=mysql.DOUBLE(asdecimal=True),
               existing_nullable=True)
        batch_op.alter_column('subscription_start_time',
               existing_type=sa.REAL(),
               type_=mysql.DOUBLE(asdecimal=True),
               existing_nullable=True)
        batch_op.alter_column('points_reset_time',
               existing_type=sa.REAL(),
               type_=mysql.DOUBLE(asdecimal=True),
               existing_nullable=True)
        batch_op.alter_column('phone_number',
               existing_type=mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_unicode_ci', length=20),
               nullable=False)
        batch_op.drop_column('oauth_id')
        batch_op.drop_column('oauth_provider')
        batch_op.drop_column('reset_token_expiry')
        batch_op.drop_column('reset_token')
        batch_op.drop_column('password_hash')
        batch_op.drop_column('email_verified')
        batch_op.drop_column('email')

    with op.batch_alter_table('SUBSCRIPTION', schema=None) as batch_op:
        batch_op.alter_column('created_at',
               existing_type=sa.REAL(),
               type_=mysql.DOUBLE(asdecimal=True),
               existing_nullable=False)
        batch_op.alter_column('payment_amount',
               existing_type=sa.REAL(),
               type_=mysql.DOUBLE(asdecimal=True),
               existing_nullable=False)
        batch_op.alter_column('end_time',
               existing_type=sa.REAL(),
               type_=mysql.DOUBLE(asdecimal=True),
               existing_nullable=False)
        batch_op.alter_column('start_time',
               existing_type=sa.REAL(),
               type_=mysql.DOUBLE(asdecimal=True),
               existing_nullable=False)

    with op.batch_alter_table('ROADMAP', schema=None) as batch_op:
        batch_op.alter_column('update_timestamp',
               existing_type=sa.REAL(),
               type_=mysql.DOUBLE(asdecimal=True),
               existing_nullable=True)
        batch_op.alter_column('create_timestamp',
               existing_type=sa.REAL(),
               type_=mysql.DOUBLE(asdecimal=True),
               existing_nullable=True)

    with op.batch_alter_table('POINTS_TRANSACTION', schema=None) as batch_op:
        batch_op.alter_column('created_at',
               existing_type=sa.REAL(),
               type_=mysql.DOUBLE(asdecimal=True),
               existing_nullable=False)
        batch_op.alter_column('expires_at',
               existing_type=sa.REAL(),
               type_=mysql.DOUBLE(asdecimal=True),
               existing_nullable=True)

    with op.batch_alter_table('POINTS_BALANCE', schema=None) as batch_op:
        batch_op.alter_column('created_at',
               existing_type=sa.REAL(),
               type_=mysql.DOUBLE(asdecimal=True),
               existing_nullable=False)
        batch_op.alter_column('expires_at',
               existing_type=sa.REAL(),
               type_=mysql.DOUBLE(asdecimal=True),
               existing_nullable=True)

    with op.batch_alter_table('PAYMENT_ORDER', schema=None) as batch_op:
        batch_op.alter_column('updated_at',
               existing_type=sa.REAL(),
               type_=mysql.DOUBLE(asdecimal=True),
               existing_nullable=False)
        batch_op.alter_column('created_at',
               existing_type=sa.REAL(),
               type_=mysql.DOUBLE(asdecimal=True),
               existing_nullable=False)
        batch_op.alter_column('payment_time',
               existing_type=sa.REAL(),
               type_=mysql.DOUBLE(asdecimal=True),
               existing_nullable=True)
        batch_op.alter_column('amount',
               existing_type=sa.REAL(),
               type_=mysql.DOUBLE(asdecimal=True),
               existing_nullable=False)

    with op.batch_alter_table('INVITATION', schema=None) as batch_op:
        batch_op.alter_column('created_at',
               existing_type=sa.REAL(),
               type_=mysql.DOUBLE(asdecimal=True),
               existing_nullable=False)

    with op.batch_alter_table('CHAT_SESSION', schema=None) as batch_op:
        batch_op.alter_column('updated_at',
               existing_type=sa.REAL(),
               type_=mysql.DOUBLE(asdecimal=True),
               existing_nullable=True)
        batch_op.alter_column('created_at',
               existing_type=sa.REAL(),
               type_=mysql.DOUBLE(asdecimal=True),
               existing_nullable=True)

    with op.batch_alter_table('CHAT_MESSAGE', schema=None) as batch_op:
        batch_op.alter_column('timestamp',
               existing_type=sa.REAL(),
               type_=mysql.DOUBLE(asdecimal=True),
               existing_nullable=True)

    # ### end Alembic commands ###
